sudo: false
dist: trusty
language: cpp

jobs:
  include:
    # Build with clang and run tests on the host system (Ubuntu).
    - &test-ubuntu
      stage: test
      compiler: clang
      python: 2.7
      node_js: 7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'g++-5']
      before_install:
        - export CC="${CC_COMPILER}"
        - export CXX="${CXX_COMPILER}"
        - export ASAN_OPTIONS="symbolize=1"
      install:
        - pip install --user flake8==3.4.1
      before_script:
        # Check the style of a subset of Python code until the other code is updated.
        - flake8 ./scripts/
        - ./check.py --test-waterfall --only-prepare
      script:
        - cmake . -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
        - make -j2
        - ./check.py --test-waterfall
      env: |
        CC_COMPILER="./test/wasm-install/wasm-install/bin/clang"
        CXX_COMPILER="./test/wasm-install/wasm-install/bin/clang++"

    # Also build wasm.js and binaryen.js using the emsdk
    - <<: *test-ubuntu
      sudo: required
      compiler: gcc
      env: |
        CC_COMPILER="gcc-5"
        CXX_COMPILER="g++-5"
      services:
      - docker
      before_install:
      - docker pull ubuntu:16.04
      script:
      - docker build .

notifications:
  email: false
